---
title: "main"
author: "Constantin Goeldel"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The epimutation profile of gbmGenes

This script analyses patterns in epimutation rates in gene-body-methylated genes.

## Get gbmGene subset of A.Thaliana genome 

```{bash}

for i in methylome_*.txt; do awk 'BEGIN{OFS="\t"}{if($0~/^1|^2|^3|^4|^5/){if($4=="CG") {print $1,$2,$2+1,$4,0,$3,$5,$6,$7,$8,$9}}}' $i > /mnt/int/MA-lines/drought/CG/methylome_CG_bed/$i.change.bed; done

for i in methylome_*.txt.change.bed; do bedtools intersect -a $i -b ~/documents/ref/Arabidopsis_thaliana/chr_states/CS-clock.bed -wa -wb -f 1|bedtools groupby -i - -g 1,2,6,4,7,8,9,10,11 -c 12 -o collapse | awk 'BEGIN{OFS="\t"} {print $1,$2,$3,$4,$5,$6,$7,$8,$9}' | sed '1i\seqnames\tstart\tstrand\tcontext\tcounts.methylated\tcounts.total\tposteriorMax\tstatus\trc.meth.lvl' - > /mnt/int/MA-lines/drought/CG/methylome_CG_CS-clock/$i.within_CS-clock.txt; done

```

```{r}
methylome_files = list.files(path="/mnt/nas/zhilin/others/MA3_new_total_original_methylome", pattern="*.txt", full.names=TRUE, recursive=FALSE)
lapply(methylome_files, function(x) {
  con = file(x, "r")
  file_name = paste(substr(x, 57, nchar(x)-4), ".change.bed") # Extract only file specific name without .txt
  i = 0
  while ( i < 50 ) {
    line = readLines(con, n = 1 )
    if ( length(line) == 0 ) {
      break
    }
    
     if (unlist(strsplit(line, "\t" ))[4] == "context") { 
       write(line, file_name, sep="\t", append = FALSE) # Clear file when writing header line
      print(line)
    }
   
    if (unlist(strsplit(line, "\t" ))[4] == "CG") {
       write(line, file_name, sep="\t", append = TRUE)
      print(line)
    }
    
    i = i +1
  }
  

  close(con)

    
})

```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
